
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace api_gamebai.Models
{

using System;
    using System.Collections.Generic;
    
public partial class history_login
{

    public int id { get; set; }

    public int player_id { get; set; }

    public Nullable<System.DateTime> login_time { get; set; }

    public Nullable<System.DateTime> logout_time { get; set; }



    public virtual player player { get; set; }

}

}
