//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_gamebai.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DatabaseGameBaiEntities1 : DbContext
    {
        public DatabaseGameBaiEntities1()
            : base("name=DatabaseGameBaiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<room_listplayer> room_listplayer { get; set; }
    
        public virtual int sendmessage(Nullable<int> playerIDsend, Nullable<int> playerIDrecive, string message)
        {
            var playerIDsendParameter = playerIDsend.HasValue ?
                new ObjectParameter("playerIDsend", playerIDsend) :
                new ObjectParameter("playerIDsend", typeof(int));
    
            var playerIDreciveParameter = playerIDrecive.HasValue ?
                new ObjectParameter("playerIDrecive", playerIDrecive) :
                new ObjectParameter("playerIDrecive", typeof(int));
    
            var messageParameter = message != null ?
                new ObjectParameter("message", message) :
                new ObjectParameter("message", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sendmessage", playerIDsendParameter, playerIDreciveParameter, messageParameter);
        }
    }
}
