//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_gamebai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class player_listfriend
    {
        public int id { get; set; }
        public int player_id { get; set; }
        public int friend_id { get; set; }
        public bool isban { get; set; }
    
        public virtual player player { get; set; }
        public virtual player player1 { get; set; }
    }
}
