//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_gamebai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vChat
    {
        public int player_id_send { get; set; }
        public int player_id_receive { get; set; }
        public bool isseen { get; set; }
        public string message { get; set; }
        public System.DateTime send_date { get; set; }
        public bool isdelete { get; set; }
    }
}
