//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_gamebai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vroom_listplayer
    {
        public int room_id { get; set; }
        public int player_id { get; set; }
        public string nickname { get; set; }
        public decimal money { get; set; }
        public string avartar { get; set; }
    }
}
